version: "3"

services:
  api:
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./uploads:/src/images