version: "3"

services:
  api:
    build: .
    ports:
      - 3333:3333
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://docker:docker@database:5432/test_database?schema=public
      - NODE_ENV=dev
      - PORT=3333
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./uploads:/src/images

  database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=test_database
